apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgAGVGqEDZvEVW1zGiX2AflPW0w9IUli++sqMiIi7z2zUwfForQsR226KMGtPklGtrI2xpnF1Dku0Dwu3AQ3/Ki1gHxGZrvLi35QNkw8B8yg3WpC6RV1aEt3WjyBV+0rpAToLVH0owOh53X60QbuLW5Hn/iY8k7hAhWm/LOqsS3Bpinb11YhDb4/Txl+v+BR/wqftuF/EkXtjz4VEoy+TjQlWCicQTcct3wSzu2+mldQdCBKXIC2C0FPLPVMJD0j2SL7kjhW1CLMmyOI8t2uEpAj6jsyr2tfdNEIbbyNcycHBjxdWuA/WZPWywoy9GgRlGdixFB46myAtioigyUvKtl1abOSwVlGb5ZhzdYeswEEp37vQpO9V4NKOFJ7QbecHq9O66DgVd3r5wEDNO+qX7rqvcwxPxj5/5YaOBrV5X0s8H3cbWP0pDYiEIDcO6MWAwJ2dzgoiODVOF18hGF2zTlosJ5k9pMKNcbLZ71bpMNOZLoHbROQbj0qZySFw7V0/AXuwkhGOK24NkvCp+7X+35NFrtd+NnB4NRSIX055y5xCdA/K9NvTafVdIdgldveEyg59zs5ZsJau3TIk/IP9JNnx0e/u61+Q8WSzaQAla2Sz1AgKsipUOI4A0lMKX0PPyF6Jw7bds1NSzfMDTrwRc0O8fN3slLcBoqznKsnXWfGnPH4W8r6JjEL/IQRdKsGMxIhBnwM07LVHsIsGPTu7rZrc+80O4QKSthxK35itK7jZqfBfGlk5BV2
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

