apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgBLuMnFpsYxDARC3Z433jZB7obaWvTYgNXhYh7hBOA9Ye3QFsAkHSRNhMYWcXW96IJ3Ro4e0V5C5sYkTZNq1gz+AXmeQ40gKFM/6OCHc6JbFnondg/IAPUlaYrEw+rD839UqKO8bqonNOz+NlWbLsNZ8c6UIPKFQ/BuaXxhRkKyItjn1D22+V7Mk5gNdiEjbhXuj6KbQWf95jrHrDBz18zXajAn3pFNVaY91DmXWt1H8zmrtwQ3keKClCPL4Patp5T8cHBS4nszGAqMBouvYWRYfL1BOB3ogc6EGU//qodYDRbcIJPxITgmkKvVAe+cFDBN9XR9NOZGjOlqWDtvRXh5hOuDDPlAjzQhEfMUFEDQlLf9KJ7NCa9y7H9Mkl6gNOjLQc/GPa+AnhmBke+kz/HTrf/SyfNsdNWbb0S8PDmFkGIPlDO2f82aCObw5K8iyUVhZzsFe8QMayUdhgX9iXQ5dWoJIXyiE4DqcspETPG8gpV/uJhi/kgpBxIpJQapaxWg6Hdfand3sHCDVOvRozX9us26lWKxrEL9TD/bqP+C4f7t9f+/BMSRg/AiwPXYpfQv6Aha4TvAtLMNJYiuOY04kIZfkZSctPlr6lyq3Sg2ibf6ivLYkp+ahqmnp9FA4sDqhAJBzRLsjhOpM8kKYT1PBl/9+nrf+ebX45lkgw4yNIOUU69JO3zVwtyuhrrpORg8IJWOt1sBb03TNP76+qOCcALGfAP0DQJpZXg2dH2/+QkzD4PAaiLZYeVL41Wopa02qXmMRQimNEimexOuKix8yuSE/+So+xMVHQ1RU/KkJkyI3QV/ZI/BaiieEIKGr1DpbDd8K8zmnqVjvkbOgvihVMu49GC6RyffDq//FiMllKJkNJTlKs10XRl+l8M8+gBQWEvI1aVaNnlwKQBd9LXinLqIt5401RZl8YkJa9vAQOOmU6JV2aExWezNuI2fT/wJvZrRF+p5Heik0BpW9vKeouJVIjAvAm+l2Qks41VS2cIE8uERhvI1pkKP9xEd+/dcFxXDxf3dRCMPjimdzqwEONsXsKhG0S4sV+Zs7aHr4m9X6PU+wwvU5R2IntbCZAi67swY0RRIDSMNxTEKTsEf8XDm743Ed2jAL4Cogd4pKh9bYpw6QM9aAJn5OCqzzu/gSReR98ejR3+qvPaYFAEECQxABpK1+Fw2YexcZIeeijUo+ZlBhpfRUg4dxbP1M7eJjcXkk5UuxMVB4+Q3Uxnvwj+bVLTBo23YpWJ9lgSRp0GLBrrfWpJ1SCsxAv3LQMuQHlAtYl+c5lIHH6v0BEieMP5WhdbNckh2aXtPnqA7VsTUqo7PAs7bL7KSg5G1N/dJQJpcMfQWkg+UsMFrKF8P1QknIuTjCV1g9JnUsGfCS3Lcr9Xf
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

